Daten werden als Numpy-Arrays gespeichert.\
numpy.arange([start, ]stop, [step, ], dtype=None) -> numpy.ndarray


In [2]:
import numpy as np # Numpy-Bibliothek importieren

# Aufgabe: Erzeugen Sie ein Array, das die Zahlen 0 bis 4 enthält! 

vector = np.arange(?) 
vector

TypeError: unsupported operand type(s) for -: 'ellipsis' and 'int'

Und können durch Indexierung oder Slicing leicht zugänglich gemacht werden.
Beispiel: \
x[2] \
Ausgabe: 2

In [3]:
print(vector[?]) # zweites Element der Liste

print(vector[?]) # Zweites Element von hinten

print(vector[?:?]) # Zweites bis drittes Element der Liste

SyntaxError: invalid syntax (<ipython-input-3-1c327ae2b6c7>, line 1)

Es können Matrizen generiert und manipuliert werden.

Die Einheitsmatrix ist eine quadratische Matrix mit Einsen auf der Hauptdiagonale. Die Funktion numpy.identity(n, dtype=None) gibt diese als n x n Array zurück. 

In [6]:
 # Erzeugen Sie eine 5x5 Einheitsmatrix!
matrix = ?

# Kopieren Sie nun oben erzeugtes Array "vector" in die dritte Spalte von "matrix"
matrix[:,?] = vector 
print(matrix)

NameError: name 'vector' is not defined

Matrixoperationen sind Eigenschaften oder Methoden:

In [7]:
# Transponieren einer Matrix
matrix = matrix.T 
print(matrix)

# Berechnen des Skalarprodukts von matrix und vector
print(np.dot(matrix, vector)) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


NameError: name 'vector' is not defined